repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  #  - id: no-commit-to-branch
  - id: pretty-format-json
    args:
    - --autofix
    - --no-ensure-ascii
  - id: sort-simple-yaml
- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: local
  hooks:
  - id: system
    name: prospector
    entry: poetry run prospector
    language: system
    files: \.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
- repo: https://github.com/myint/rstcheck
  rev: "3f92957478422df87bd730abde66f089cc1ee19b"
  hooks:
  - id: rstcheck
