version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  lint:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run linters
        command: poetry run prospector . -s veryhigh
  static-analysis:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run mypy
        command: poetry run mypy sarada tests
  test:
    parallelism: 4
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run tests
        command: |
          set -e
          TEST_FILES=$(circleci tests glob "**/*.py" | circleci tests split --split-by=timings)
          mkdir -p test-results
          poetry run pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES
    - store_test_results:
        path: test-results
  build:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Build
        command: poetry build
    - store_artifacts:
      path: "dist/"
workflows:
  test:
    jobs:
    - lint
    - static-analysis
    - test
  build:
    jobs:
    - build:
      requires:
      - test
      filter:
        branches:
          ignore: /.*/
        tags:
          only: /.*/
