version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  lint:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run linters
        command: poetry run prospector . -s veryhigh
  static-analysis:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run mypy
        command: poetry run mypy sarada tests
  test:
    docker:
    - image: cimg/python:3.9
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run tests
        command: poetry run pytest

workflows:
  test:
    jobs:
    - lint
    - static-analysis
    - test
